// src/data/products.js
import electronic from '../assets/images/electronic.jpg';
import furniture from '../assets/images/furniture.jpg';
import books from '../assets/images/books.jpg'; 

export const products = [
  {
    productID: "1",
    imageids: [electronic],
    title: "Dell Laptop",
    price: "500",
    category: "Electronics",
  },
  {
    productID: "2",
    imageids: [furniture],
    title: "Foldable Bed",
    price: "300",
    category: "Furniture",
  },
  {
    productID: "3",
    imageids: [books],
    title: "Harry Potter Books",
    price: "150",
    category: "Books",
  },
  {
    productID: "4",
    imageids: [electronic],
    title: "Sample Product 4",
    price: "450",
    category: "Electronics",
  },
  {
    productID: "5",
    imageids: [furniture],
    title: "Sample Product 5",
    price: "350",
    category: "Furniture",
  },
  {
    productID: "6",
    imageids: [books],
    title: "Sample Product 6",
    price: "200",
    category: "Books",
  },
  {
    productID: "7",
    imageids: [electronic],
    title: "Sample Product 7",
    price: "600",
    category: "Electronics",
  },
  {
    productID: "8",
    imageids: [furniture],
    title: "Sample Product 8",
    price: "400",
    category: "Furniture",
  },
  {
    productID: "9",
    imageids: [books],
    title: "Sample Product 9",
    price: "180",
    category: "Books",
  },
  {
    productID: "10",
    imageids: [electronic],
    title: "Sample Product 10",
    price: "550",
    category: "Electronics",
  },
  {
    productID: "11",
    imageids: [furniture],
    title: "Sample Product 11",
    price: "370",
    category: "Furniture",
  },
  {
    productID: "12",
    imageids: [books],
    title: "Sample Product 12",
    price: "120",
    category: "Books",
  },
  {
    productID: "13",
    imageids: [electronic],
    title: "Sample Product 13",
    price: "500",
    category: "Electronics",
  },
  {
    productID: "14",
    imageids: [furniture],
    title: "Sample Product 14",
    price: "330",
    category: "Furniture",
  },
  {
    productID: "15",
    imageids: [books],
    title: "Sample Product 15",
    price: "160",
    category: "Books",
  },
  {
    productID: "16",
    imageids: [electronic],
    title: "Sample Product 16",
    price: "480",
    category: "Electronics",
  },
  {
    productID: "17",
    imageids: [furniture],
    title: "Sample Product 17",
    price: "310",
    category: "Furniture",
  },
  {
    productID: "18",
    imageids: [books],
    title: "Sample Product 18",
    price: "140",
    category: "Books",
  },
  {
    productID: "19",
    imageids: [electronic],
    title: "Sample Product 19",
    price: "570",
    category: "Electronics",
  },
  {
    productID: "20",
    imageids: [furniture],
    title: "Sample Product 20",
    price: "320",
    category: "Furniture",
  },
];
